export const POST_TO_LIST_REQUEST = "POST_TO_LIST_REQUEST";
export const POST_TO_LIST_SUCCESS = "POST_TO_LIST_SUCCESS";
export const POST_TO_LIST_FAILURE = "POST_TO_LIST_FAILURE";


export const GET_TO_LIST_REQUEST = "POST_TO_LIST_REQUEST";
export const GET_TO_LIST_SUCCESS = "POST_TO_LIST_SUCCESS";
export const GET_TO_LIST_FAILURE = "POST_TO_LIST_FAILURE";

